# in dvc.yaml
stages:
  collect_data:
    cmd: python scripts/collect_data.py
    deps:
      - scripts/collect_data.py
    outs:
      - data/raw_data.csv
      
  preprocess_data:
    cmd: python scripts/preprocess_data.py
    deps:
      - scripts/preprocess_data.py
      - data/raw_data.csv
    outs:
      - data/processed_data.csv
      
  train_model:
    cmd: python scripts/train_model.py
    deps:
      - scripts/train_model.py
      - data/processed_data.csv
    outs:
      - models/model.pkl
    metrics:
      - metrics.json:
          cache: false
          
  test_model:
    cmd: python scripts/test_model.py
    deps:
      - scripts/test_model.py
      - data/processed_data.csv
      - models/model.pkl
    metrics:
      - metrics_test.json:
          cache: false
    plots:
      - models/classification_evaluation.png