apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: mlops-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-frontend
  template:
    metadata:
      labels:
        app: mlops-frontend
    spec:
      containers:
      - name: mlops-frontend
        image: mlops-frontend:latest
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "http://localhost:5000"  # This will be overridden by port forwarding
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: mlops-frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP