apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-standalone
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: python:3.11-slim
        ports:
        - containerPort: 5001
        command:
        - sh
        - -c
        - |
          pip install mlflow psycopg2-binary
          mlflow server \
            --host 0.0.0.0 \
            --port 5001 \
            --backend-store-uri sqlite:///mlflow.db \
            --default-artifact-root /mlruns
        volumeMounts:
        - name: mlflow-data
          mountPath: /mlflow.db
        - name: mlflow-artifacts
          mountPath: /mlruns
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: mlflow-data
        emptyDir: {}
      - name: mlflow-artifacts
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  selector:
    app: mlflow
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP
