apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-simple
  labels:
    app: mlflow-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-simple
  template:
    metadata:
      labels:
        app: mlflow-simple
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:v2.10.2
        ports:
        - containerPort: 5001
        command:
        - mlflow
        - server
        - --host=0.0.0.0
        - --port=5001
        - --backend-store-uri=sqlite:///mlflow.db
        - --default-artifact-root=/mlruns
        volumeMounts:
        - name: mlflow-data
          mountPath: /mlflow
        - name: mlflow-artifacts
          mountPath: /mlruns
        workingDir: /mlflow
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
      volumes:
      - name: mlflow-data
        emptyDir: {}
      - name: mlflow-artifacts
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-simple-service
spec:
  selector:
    app: mlflow-simple
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP
