apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      initContainers:
      - name: mlflow-init
        image: ghcr.io/mlflow/mlflow:v2.10.2
        env:
        - name: MLFLOW_DB_URI
          value: "postgresql://postgres:password@postgres-service:5432/mlops"
        command:
        - sh
        - -c
        - |
          pip install psycopg2-binary
          # Initialize the database schema
          python -c "
          import mlflow
          import mlflow.store.db.utils
          mlflow.store.db.utils.create_db_tables_if_not_exists('$MLFLOW_DB_URI')
          "
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:v2.10.2
        ports:
        - containerPort: 5001
        command:
        - mlflow
        - server
        - --host=0.0.0.0
        - --port=5001
        - --backend-store-uri=postgresql://postgres:password@postgres-service:5432/mlops
        - --default-artifact-root=/mlruns
        - --serve-artifacts
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        volumeMounts:
        - name: mlflow-artifacts
          mountPath: /mlruns
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: mlflow-artifacts
        persistentVolumeClaim:
          claimName: mlflow-artifacts-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  selector:
    app: mlflow
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-artifacts-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
